apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: was8-demo-v1-deployment
  labels:
    app: was8-demo-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: was8-demo-v1
  template:
    metadata:
      labels:
        app: was8-demo-v1
    spec:
      containers:
      - name: was8-demo-v1
        image: 033565913883.dkr.ecr.eu-west-1.amazonaws.com/smartnimbus/was8-demo:1.0.3
        
---
apiVersion: v1
kind: Service
metadata:
  name: was8-demo-v1-service
  labels:
    app: was8-demo-v1
spec:
  ports:
  - port: 9043
    name: http-9043
    protocol: TCP
  - port: 9443
    name: http-9443
    protocol: TCP
  type: LoadBalancer
  selector:
        app: was8-demo-v1